# Generated by Django 5.0.6 on 2024-07-15 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_user_dob_user_gender_user_phone_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='drinking',
            field=models.CharField(choices=[('N', 'Non-Drinker'), ('O', 'Ocaasional Drinker'), ('R', 'Regular Drinker')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rel_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow'), ('D', 'Divorced')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='short_reel',
            field=models.FileField(default=None, null=True, upload_to='short_reels/'),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.CharField(choices=[('N', 'Non-Smoker'), ('O', 'Occasional Smoker'), ('R', 'Regular Smoker')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='EmployeeEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
