# Generated by Django 5.0.6 on 2024-07-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_unique_together_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Expert')], default='B', max_length=1),
        ),
    ]
